const statsLabels = {
    en: {
        tableCaption: 'LGS1920 Studio usage counters by the viewer’s local period',
        period:       'Period',
        visits:       'Visits',
        journeys:     'Journeys',
        videoDraft:   'Draft videos',
        videoHq:      'HQ videos',
        total:        'Total',
        today:        'Today',
        yesterday:    'Yesterday',
        thisWeek:     'This week',
        thisMonth:    'This month',
        previousMonth:'Last month',
        thisYear:     'This year',
        loading:      'Loading counters…',
        loaded:       'Counters loaded.',
        partial:      'Some counters are temporarily unavailable.',
        failed:       'Counters could not be loaded right now.',
        refreshing:   'Refreshing counters…',
        updated:      'Last update:',
        refresh:      'Refresh',
        unavailable:  'Unavailable',
    },
    fr: {
        tableCaption: 'Compteurs d’utilisation de LGS1920 Studio selon la période locale du visiteur',
        period:       'Période',
        visits:       'Visites',
        journeys:     'Parcours',
        videoDraft:   'Vidéos brouillon',
        videoHq:      'Vidéos HQ',
        total:        'Total',
        today:        'Aujourd’hui',
        yesterday:    'Hier',
        thisWeek:     'Cette semaine',
        thisMonth:    'Ce mois-ci',
        previousMonth:'Le mois dernier',
        thisYear:     'Cette année',
        loading:      'Chargement des compteurs…',
        loaded:       'Compteurs chargés.',
        partial:      'Certains compteurs sont temporairement indisponibles.',
        failed:       'Les compteurs ne peuvent pas être chargés pour le moment.',
        refreshing:   'Actualisation des compteurs…',
        updated:      'Dernière mise à jour :',
        refresh:      'Actualiser',
        unavailable:  'Indisponible',
    },
}

export const getStatsLabels = (locale = 'en') => statsLabels[locale] ?? statsLabels.en

export default statsLabels
