const contact = {
    layout:   'layouts/page.html',
    requiresBackend:true,
    pageClass:'contact-page',
    path:     '/contact/',
    en:       {
        title:       'Contact LGS1920',
        description: 'Send a message to the LGS1920 Studio team through a privacy-conscious contact form.',
        hero:        {
            video:     false,
            badge:     'Contact',
            kicker:    'Get in touch',
            title:     'Tell us what you need.',
            lead:      'Use this form for questions about Studio, the website, licensing, partnerships, or anything else you would like to share with LGS1920.',
            highlights:[
                {label:'A direct reply', icon:'paper-plane', variant:'regular'},
                {label:'Clear consent', icon:'shield-check', variant:'regular'},
                {label:'No advertising reuse', icon:'lock', variant:'regular'},
            ],
        },
        sectionNav: [
            {id:'contact-form', label:'Contact form', summary:'Send your message to LGS1920'},
            {id:'contact-privacy', label:'Your data', summary:'How contact requests are handled'},
        ],
        form: {
            firstNameLabel:      'First name',
            firstNamePlaceholder:'Your first name',
            lastNameLabel:       'Last name',
            lastNamePlaceholder: 'Your last name',
            emailLabel:          'Email address',
            emailPlaceholder:   'you@example.com',
            subjectLabel:        'Subject',
            subjectPlaceholder: 'What can we help with?',
            messageLabel:        'Message',
            messagePlaceholder:  'Write your message here',
            consentLabel:        'I agree to be contacted about this request.',
            submitLabel:         'Send message',
            successMessage:      'Thank you. Your message has been sent.',
            errorMessage:        'Your message could not be sent. Please try again later.',
        },
        privacy: {
            title:   'A limited and transparent use of your message.',
            body:    'The details you provide are used only to answer your request. They are not sold or shared for advertising. You can ask for access, correction, or deletion of your data, or withdraw your consent, by sending a new request through this form or by writing to studio@lgs1920.fr.',
            notice:  'Only the information needed to answer your request is retained for as long as necessary. The form includes an anti-spam field and does not require an account.',
        },
    },
    fr:       {
        title:       'Contacter LGS1920',
        description: 'Écrivez à l’équipe LGS1920 Studio avec un formulaire de contact respectueux de votre vie privée.',
        hero:        {
            video:     false,
            badge:     'Contact',
            kicker:    'Nous écrire',
            title:     'Dites-nous ce dont vous avez besoin.',
            lead:      'Utilisez ce formulaire pour vos questions sur Studio, le site, les licences, les partenariats ou tout autre sujet à partager avec LGS1920.',
            highlights:[
                {label:'Une réponse directe', icon:'paper-plane', variant:'regular'},
                {label:'Consentement clair', icon:'shield-check', variant:'regular'},
                {label:'Aucune réutilisation publicitaire', icon:'lock', variant:'regular'},
            ],
        },
        sectionNav: [
            {id:'contact-form', label:'Formulaire de contact', summary:'Envoyer votre message à LGS1920'},
            {id:'contact-privacy', label:'Vos données', summary:'Traitement des demandes de contact'},
        ],
        form: {
            firstNameLabel:      'Prénom',
            firstNamePlaceholder:'Votre prénom',
            lastNameLabel:       'Nom',
            lastNamePlaceholder: 'Votre nom',
            emailLabel:          'Adresse e-mail',
            emailPlaceholder:   'vous@exemple.fr',
            subjectLabel:        'Objet',
            subjectPlaceholder: 'Comment pouvons-nous vous aider ?',
            messageLabel:        'Message',
            messagePlaceholder:  'Écrivez votre message ici',
            consentLabel:        'J’accepte d’être recontacté au sujet de cette demande.',
            submitLabel:         'Envoyer le message',
            successMessage:      'Merci. Votre message a bien été envoyé.',
            errorMessage:        'Votre message n’a pas pu être envoyé. Veuillez réessayer plus tard.',
        },
        privacy: {
            title:   'Un usage limité et transparent de votre message.',
            body:    'Les informations transmises servent uniquement à répondre à votre demande. Elles ne sont ni revendues ni partagées à des fins publicitaires. Vous pouvez demander l’accès, la rectification ou la suppression de vos données, ou retirer votre consentement, en envoyant une nouvelle demande via ce formulaire ou en écrivant à studio@lgs1920.fr.',
            notice:  'Seules les informations nécessaires à votre réponse sont conservées pendant la durée utile. Le formulaire comprend un champ anti-spam et ne nécessite pas de compte.',
        },
    },
}

export default contact
