const launchRegistration = {
    layout:   'layouts/page.html',
    minimalChrome:true,
    requiresBackend:true,
    pageClass:'launch-registration-page',
    path:     '/registration/',
    en:       {
        title:       'Studio launch registration',
        description: 'Register to be notified when LGS1920 Studio launches and learn about the communication channels available afterwards.',
        hero:        {
            className:'intro-hero registration-hero',
            localeSwitcher:true,
            title:    'Turn outdoors adventures into shared stories.',
            lead:     'Walk, run or ride, then import, edit, replay and share videos of your journeys without leaving your browser.',
            panel:    {
                eyebrow:'LGS1920 Studio',
                title:  'A browser workspace for journeys, camera control, capture, and reports.',
                items:  [
                    {icon:'route', title:'Import and review', text:'GeoJSON, GPX, and KML'},
                    {icon:'camera', title:'Direct the scene', text:'2D/3D, layers, and widgets'},
                    {icon:'file-pdf', title:'Export and share', text:'Snapshots, video, and reports'},
                ],
            },
        },
        sectionNav: [
            {id:'registration-form', label:'Registration form', summary:'Enter your details and consent'},
            {id:'registration-privacy', label:'Your data', summary:'How the registration data is used'},
        ],
        form: {
            firstNameLabel: 'First name',
            firstNamePlaceholder: 'Your first name',
            lastNameLabel: 'Last name',
            lastNamePlaceholder: 'Your last name',
            emailLabel: 'Email address',
            emailPlaceholder: 'you@example.com',
            consentLabel: 'I agree to be contacted when Studio launches.',
            submitLabel: 'Notify me at launch',
            successMessage: 'Thank you. Your launch registration has been recorded.',
            errorMessage: 'The registration could not be saved. Please try again later.',
        },
        privacy: 'Your details are used only to contact you about the Studio launch. They are not sold or shared for advertising. You can withdraw your consent or request access, correction, or deletion at any time by writing to studio@lgs1920.fr. We keep the registration only for the launch information period and review it afterwards.',
        licenseReminder: 'This site and Studio are distributed under the GNU Affero General Public License v3 or later.',
        licenseLink:     'Read the license',
    },
    fr:       {
        title:       'Inscription au lancement de Studio',
        description: 'Inscrivez-vous pour être averti du lancement de LGS1920 Studio et découvrir ensuite nos canaux de communication.',
        hero:        {
            className:'intro-hero registration-hero',
            localeSwitcher:true,
            title:    'Transformez vos aventures outdoor en histoires à partager.',
            lead:     'Marchez, courrez ou roulez, puis importez, éditez et partagez des vidéos de vos parcours sans quitter votre navigateur*',
            panel:    {
                eyebrow:'LGS1920 Studio',
                title:  'Un espace de travail dans le navigateur pour les parcours, la caméra, les captures et les rapports.',
                items:  [
                    {icon:'route', title:'Importer et relire', text:'GeoJSON, GPX et KML'},
                    {icon:'camera', title:'Diriger la scène', text:'2D/3D, couches et widgets'},
                    {icon:'file-pdf', title:'Exporter et partager', text:'Captures, vidéos et rapports'},
                ],
            },
        },
        sectionNav: [
            {id:'registration-form', label:'Formulaire d’inscription', summary:'Renseigner vos coordonnées et votre consentement'},
            {id:'registration-privacy', label:'Vos données', summary:'Utilisation des données d’inscription'},
        ],
        form: {
            firstNameLabel: 'Prénom',
            firstNamePlaceholder: 'Votre prénom',
            lastNameLabel: 'Nom',
            lastNamePlaceholder: 'Votre nom',
            emailLabel: 'Adresse e-mail',
            emailPlaceholder: 'vous@exemple.fr',
            consentLabel: 'J’accepte d’être recontacté lors du lancement du Studio.',
            submitLabel: 'M’avertir du lancement',
            successMessage: 'Merci. Votre inscription au lancement a bien été enregistrée.',
            errorMessage: 'L’inscription n’a pas pu être enregistrée. Veuillez réessayer plus tard.',
        },
        privacy: 'Vos coordonnées servent uniquement à vous recontacter lors du lancement du Studio. Elles ne sont ni revendues ni transmises à des fins publicitaires. Vous pouvez retirer votre consentement ou demander l’accès, la rectification ou la suppression de vos données à tout moment en écrivant à studio@lgs1920.fr. L’inscription est conservée pendant la période d’information sur le lancement, puis réévaluée.',
        licenseReminder: 'Ce site et Studio sont distribués sous licence GNU Affero General Public License v3 ou ultérieure.',
        licenseLink:     'Lire la licence',
    },
}

export default launchRegistration
