const launchRegistration = {
    layout:   'layouts/page.html',
    minimalChrome:true,
    requiresBackend:true,
    pageClass:'launch-registration-page',
    path:     '/registration/',
    en:       {
        title:       'LGS1920 Studio launch registration',
        description: 'Register to receive launch updates and learn how to stay connected afterwards.',
        registrationIntro: 'Register to receive launch updates and learn how to stay connected afterwards.',
        hero:        {
            className:'intro-hero registration-hero',
            localeSwitcher:true,
            title:    'Live outdoor adventures, share the stories.',
            lead:     'Walk, run or ride, then import, edit, replay and share videos of your journeys without leaving your browser.',
            panel:    {
                eyebrow:'LGS1920 Studio',
                title:  'Something amazing is on the way.',
                action: {label:'Stay Tuned', appearance:'filled', variant:'brand'},
                description: 'We are working hard to bring you a new experience.',
                descriptionBreak: 'Be one of the first to know when we launch and get early access.',
                items:  [
                    {icon:'route', title:'Import your trail, ride or trek and review it.', text:'GeoJSON, GPX, and KML'},
                    {icon:'camera', title:'Explore a global, 3D playground!', text:'Worldwide layers and dynamic widgets (profiles, live data, compass, text, and more to come).'},
                    {icon:'file-pdf', title:'Export and share', text:'Share videos of your adventures on social networks and export HTML or PDF reports.'},
                    ],
                promise: {
                    icon: 'lock',
                    text: 'Privacy and access for everyone.',
                    items: [
                        {icon:'location-pin-lock', title:'Privacy first', text:'Your data stays with you: browser, device, or cloud*.', note:'Cloud access will be available in a future version.', noteLabel:'More about cloud access'},
{icon:'circle-check', title:'Studio is free', text:'Studio is completely free and will remain so.', note:'Some external services accessible through Studio may be paid services from their providers. Studio has no affiliation with any of the providers concerned.', noteLabel:'More about external services'},
                    ],
                },
            },
        },
        sectionNav: [
            {id:'registration-details', label:'Something amazing is on the way', summary:'Discover what is coming to Studio'},
            {id:'registration-form', label:'Registration form', summary:'Enter your details and consent'},
            {id:'registration-privacy', label:'Your data', summary:'How the registration data is used'},
        ],
        form: {
            firstNameLabel: 'First name',
            firstNamePlaceholder: 'Your first name',
            lastNameLabel: 'Last name',
            lastNamePlaceholder: 'Your last name',
            emailLabel: 'Email address',
            emailPlaceholder: 'you@example.com',
            consentLabel: 'I agree to be contacted when Studio launches.',
            submitLabel: 'Notify me at launch',
            successMessage: 'A confirmation email has just been sent to you. Click the link it contains to complete your registration. Check your spam folder if you do not receive it.',
            duplicateMessage: 'This email address is already registered for the Studio launch.',
            pendingMessage: 'A confirmation email is already pending for this email address.',
            resendButtonLabel: 'Resend',
            resendSuccessMessage: 'A new confirmation email has been sent. Please check your inbox.',
            resendErrorMessage: 'The confirmation email could not be sent. Please try again later.',
            resendRateLimitMessage: 'Too many attempts. Please wait before trying again.',
            deliveryErrorMessage: 'The registration was saved, but the confirmation email could not be sent. Please try again later.',
            rateLimitMessage: 'Too many attempts. Please wait before trying again.',
            errorMessage: 'The registration could not be saved. Please try again later.',
        },
        privacy: 'Your details are used only to contact you about the Studio launch. They are not sold or shared for advertising. You can withdraw your consent or request access, correction, or deletion at any time by writing to studio@lgs1920.fr. We keep your registration data only for the launch information period, then review it.',
    },
    fr:       {
        title:       'Inscription au lancement de LGS1920 Studio',
        description: 'Inscrivez-vous pour recevoir les informations sur le lancement et savoir comment rester en contact ensuite.',
        registrationIntro: 'Inscrivez-vous pour recevoir les informations sur le lancement et savoir comment rester en contact ensuite.',
        hero:        {
            className:'intro-hero registration-hero',
            localeSwitcher:true,
            title:    'Vivez vos aventures outdoor, partagez vos histoires.',
            lead:     'Marchez, courez ou roulez, puis importez, éditez, rejouez et partagez les vidéos de vos parcours sans quitter votre navigateur.',
            panel:    {
                eyebrow:'LGS1920 Studio',
                title:  'Quelque chose de sympa arrive.',
                action: {label:'Restez informé', appearance:'filled', variant:'brand'},
                description: 'Nous travaillons pour vous proposer une nouvelle expérience.',
                descriptionBreak: 'Soyez parmi les premiers informés du lancement et bénéficiez d’un accès anticipé.',
                items:  [
                    {icon:'route', title:'Importez et relisez vos parcours, sorties et randonnées.', text:'GeoJSON, GPX et KML'},
                    {icon:'camera', title:'Explorez un terrain de jeu mondial en 3D !', text:'Couches mondiales et widgets dynamiques (profils, données en direct, boussole, textes et bien plus à venir).'},
                    {icon:'file-pdf', title:'Exportez et partagez', text:'Partagez les vidéos de vos aventures sur les réseaux sociaux et exportez des rapports HTML ou PDF.'},
                ],
                promise: {
                    icon: 'lock',
                    text: 'Confidentialité et accès pour tous.',
                    items: [
                        {icon:'location-pin-lock', title:'Confidentialité', text:'Vos données restent chez vous : navigateur, appareil ou cloud*.', note:'L’accès cloud sera possible dans une prochaine version.', noteLabel:'En savoir plus sur l’accès cloud'},
{icon:'gift', title:'Studio gratuit', text:'Studio est entièrement gratuit et le restera.', note:'Certains services externes accessibles depuis Studio peuvent être payants auprès de leurs fournisseurs. Studio n’a aucune affiliation avec les fournisseurs concernés.', noteLabel:'En savoir plus sur les services externes'},
                    ],
                },
            },
        },
        sectionNav: [
            {id:'registration-details', label:'Quelque chose de sympa arrive', summary:'Découvrir ce qui arrive dans Studio'},
            {id:'registration-form', label:'Formulaire d’inscription', summary:'Renseigner vos coordonnées et votre consentement'},
            {id:'registration-privacy', label:'Vos données', summary:'Utilisation des données d’inscription'},
        ],
        form: {
            firstNameLabel: 'Prénom',
            firstNamePlaceholder: 'Votre prénom',
            lastNameLabel: 'Nom',
            lastNamePlaceholder: 'Votre nom',
            emailLabel: 'Adresse e-mail',
            emailPlaceholder: 'vous@exemple.fr',
            consentLabel: 'J’accepte d’être recontacté lors du lancement du Studio.',
            submitLabel: 'M’avertir du lancement',
            successMessage: 'Un e-mail de confirmation vient de vous être envoyé. Cliquez sur le lien qu’il contient pour finaliser votre inscription. Vérifiez vos pourriels si vous ne le recevez pas.',
            duplicateMessage: 'Cette adresse e-mail est déjà inscrite au lancement du Studio.',
            pendingMessage: 'Un e-mail de confirmation est déjà en attente pour cette adresse.',
            resendButtonLabel: 'Renvoyer',
            resendSuccessMessage: 'Un nouvel e-mail de confirmation vient d’être envoyé. Consultez votre boîte de réception.',
            resendErrorMessage: 'L’e-mail de confirmation n’a pas pu être envoyé. Veuillez réessayer plus tard.',
            resendRateLimitMessage: 'Trop de tentatives. Veuillez patienter avant de réessayer.',
            deliveryErrorMessage: 'L’inscription est enregistrée, mais l’e-mail de confirmation n’a pas pu être envoyé. Veuillez réessayer plus tard.',
            rateLimitMessage: 'Trop de tentatives. Veuillez patienter avant de réessayer.',
            errorMessage: 'L’inscription n’a pas pu être enregistrée. Veuillez réessayer plus tard.',
        },
        privacy: 'Vos coordonnées servent uniquement à vous recontacter lors du lancement du Studio. Elles ne sont ni revendues ni transmises à des fins publicitaires. Vous pouvez retirer votre consentement ou demander l’accès, la rectification ou la suppression de vos données à tout moment en écrivant à studio@lgs1920.fr. Nous conservons vos données d’inscription uniquement pendant la période d’information sur le lancement, puis nous les réévaluons.',
    },
}

export default launchRegistration
