const launchRegistration = {
    layout:   'layouts/page.html',
    minimalChrome:true,
    requiresBackend:true,
    pageClass:'launch-registration-page',
    path:     '/registration/',
    en:       {
        title:       'LGS1920 Studio launch registration',
        description: 'Register to receive launch updates and learn how to stay connected afterwards.',
        registrationIntro: 'Register to receive launch updates and learn how to stay connected afterwards.',
        hero:        {
            className:'intro-hero registration-hero',
            localeSwitcher:true,
            title:    'Turn outdoor adventures into shared stories.',
            lead:     'Walk, run or ride, then import, edit, replay and share videos of your journeys without leaving your browser.',
            panel:    {
                eyebrow:'LGS1920 Studio',
                title:  'Something amazing is on the way.',
                description: 'We are working hard to bring you a new experience.',
                descriptionBreak: 'Be one of the first to know when we launch and get early access.',
                items:  [
                    {icon:'route', title:'Import your trail, ride or trek and review it.', text:'GeoJSON, GPX, and KML'},
                    {icon:'camera', title:'Explore a global, 3D playground!', text:'Worldwide layers and dynamic widgets (profiles, live data, compass, text, and more to come).'},
                    {icon:'file-pdf', title:'Export and share', text:'Share videos of your adventures on social networks and export HTML or PDF reports.'},
                    ],
                promise: {
                    icon: 'lock',
                    text: 'Privacy and access for everyone.',
                    items: [
                        {icon:'location-pin-lock', title:'Privacy first', text:'Your data stays in your browser, on your device, or in your cloud.'},
                        {icon:'circle-check', title:'Completely free!', text:'Stop paying for certain features: Studio provides them for free.'},
                    ],
                },
            },
        },
        sectionNav: [
            {id:'registration-form', label:'Registration form', summary:'Enter your details and consent'},
            {id:'registration-privacy', label:'Your data', summary:'How the registration data is used'},
        ],
        form: {
            firstNameLabel: 'First name',
            firstNamePlaceholder: 'Your first name',
            lastNameLabel: 'Last name',
            lastNamePlaceholder: 'Your last name',
            emailLabel: 'Email address',
            emailPlaceholder: 'you@example.com',
            consentLabel: 'I agree to be contacted when Studio launches.',
            submitLabel: 'Notify me at launch',
            successMessage: 'Thank you. Your launch registration has been recorded.',
            errorMessage: 'The registration could not be saved. Please try again later.',
        },
        privacy: 'Your details are used only to contact you about the Studio launch. They are not sold or shared for advertising. You can withdraw your consent or request access, correction, or deletion at any time by writing to studio@lgs1920.fr. We keep your registration data only for the launch information period, then review it.',
        licenseReminder: 'This site and Studio are distributed under the GNU Affero General Public License v3 or later.',
        licenseLink:     'Read the license',
    },
    fr:       {
        title:       'Inscription au lancement de LGS1920 Studio',
        description: 'Inscrivez-vous pour recevoir les informations sur le lancement et savoir comment rester en contact ensuite.',
        registrationIntro: 'Inscrivez-vous pour recevoir les informations sur le lancement et savoir comment rester en contact ensuite.',
        hero:        {
            className:'intro-hero registration-hero',
            localeSwitcher:true,
            title:    'Transformez vos aventures outdoor en histoires à partager.',
            lead:     'Marchez, courez ou roulez, puis importez, éditez, rejouez et partagez les vidéos de vos parcours sans quitter votre navigateur.',
            panel:    {
                eyebrow:'LGS1920 Studio',
                title:  'Quelque chose de sympa arrive.',
                description: 'Nous travaillons pour vous proposer une nouvelle expérience.',
                descriptionBreak: 'Soyez parmi les premiers informés du lancement et bénéficiez d’un accès anticipé.',
                items:  [
                    {icon:'route', title:'Importez et relisez vos parcours, sorties et randonnées.', text:'GeoJSON, GPX et KML'},
                    {icon:'camera', title:'Explorez un terrain de jeu mondial en 3D !', text:'Couches mondiales et widgets dynamiques (profils, données en direct, boussole, textes et bien plus à venir).'},
                    {icon:'file-pdf', title:'Exportez et partagez', text:'Partagez les vidéos de vos aventures sur les réseaux sociaux et exportez des rapports HTML ou PDF.'},
                ],
                promise: {
                    icon: 'lock',
                    text: 'La confidentialité et l’accès pour tous.',
                    items: [
                        {icon:'location-pin-lock', title:'La confidentialité avant tout', text:'Vos données restent dans votre navigateur, sur votre appareil ou dans votre cloud.'},
                        {icon:'circle-check', title:'Totalement gratuit !', text:'Arrêtez de payer pour certaines fonctionnalités : Studio vous les fournit gratuitement.'},
                    ],
                },
            },
        },
        sectionNav: [
            {id:'registration-form', label:'Formulaire d’inscription', summary:'Renseigner vos coordonnées et votre consentement'},
            {id:'registration-privacy', label:'Vos données', summary:'Utilisation des données d’inscription'},
        ],
        form: {
            firstNameLabel: 'Prénom',
            firstNamePlaceholder: 'Votre prénom',
            lastNameLabel: 'Nom',
            lastNamePlaceholder: 'Votre nom',
            emailLabel: 'Adresse e-mail',
            emailPlaceholder: 'vous@exemple.fr',
            consentLabel: 'J’accepte d’être recontacté lors du lancement du Studio.',
            submitLabel: 'M’avertir du lancement',
            successMessage: 'Merci. Votre inscription au lancement a bien été enregistrée.',
            errorMessage: 'L’inscription n’a pas pu être enregistrée. Veuillez réessayer plus tard.',
        },
        privacy: 'Vos coordonnées servent uniquement à vous recontacter lors du lancement du Studio. Elles ne sont ni revendues ni transmises à des fins publicitaires. Vous pouvez retirer votre consentement ou demander l’accès, la rectification ou la suppression de vos données à tout moment en écrivant à studio@lgs1920.fr. Nous conservons vos données d’inscription uniquement pendant la période d’information sur le lancement, puis nous les réévaluons.',
        licenseReminder: 'Ce site et Studio sont distribués sous licence GNU Affero General Public License v3 ou ultérieure.',
        licenseLink:     'Lire la licence',
    },
}

export default launchRegistration
